# Generated by Django 4.2.6 on 2023-12-26 14:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Код купону')),
                ('valid_form', models.DateTimeField(verbose_name='З якої дати дійсний')),
                ('valid_to', models.DateTimeField(verbose_name='По яку дату дійсний')),
                ('discount', models.IntegerField(help_text='Відсоткове значення (від 0 до 100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Знижка у %')),
                ('active', models.BooleanField(verbose_name='чи є купон активним/ неактивним')),
            ],
        ),
    ]
