# Generated by Django 4.2 on 2023-07-30 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_category_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sizes_clothing',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sizes_shoes',
        ),
        migrations.DeleteModel(
            name='Size',
        ),
        migrations.DeleteModel(
            name='SizeShoes',
        ),
    ]
