# Generated by Django 4.2 on 2023-08-14 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_product_specification'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='mini_description',
            field=models.TextField(blank=True, verbose_name='Міні опис'),
        ),
    ]
