# Generated by Django 4.2.6 on 2023-11-22 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='oder_notes',
            field=models.TextField(blank=True),
        ),
    ]
